/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Utils;

/**
 *
 * @author iband
 */
public class FrAltUsuario extends javax.swing.JDialog {
  //código do usuário que irá alterar
  private int pkusuario;
  
  public void setPkusuario(int pkusuario){
    this.pkusuario = pkusuario;
  }
  
  /**
   * Creates new form FrAltUsuario
   */
  public FrAltUsuario(java.awt.Frame parent, boolean modal, int pkusuario) {
    super(parent, modal);
    initComponents();
    
    //tira a referência da posição, abrindo centralizado
    this.setLocationRelativeTo(null);
    
    setPkusuario(pkusuario);
    //carregar os dados deste usuário
    carregarUsuario();
  }

  public void carregarUsuario() {
    //vamos buscar no banco de dados o restante
    //dos campos do usuario, atualmente só
    //tem o pk

    UsuarioController controller = new UsuarioController();
    Usuario usuario = controller.buscarPorPk(pkusuario);

    String codigo = String.valueOf(usuario.getId_cliente());
    edtCodigo.setText(codigo);
    edtNome.setText(usuario.getNome());
    edtEmail.setText(usuario.getEmail());
    edtDataNasc.setText(Utils.converterDateToString(usuario.getDataNasc()));
    chkAtivo.setSelected(usuario.isAtivo());

  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmaSenha = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        edtConfirmaSenha = new javax.swing.JPasswordField();
        edtSenha = new javax.swing.JPasswordField();
        edtDataNasc = new javax.swing.JFormattedTextField();
        chkAtivo = new javax.swing.JCheckBox();
        btnAlterarSenha = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ateração de Usuário");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Alteração de Usuário");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("ID");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        edtCodigo.setEditable(false);
        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        edtEmail.setBackground(null);
        edtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 380, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Email");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setText("Senha");
        jPanel1.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        lblConfirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConfirmaSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblConfirmaSenha.setText("Confirma senha");
        jPanel1.add(lblConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        lblDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        lblDataNasc.setText("Data de Nascimento");
        jPanel1.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        edtConfirmaSenha.setEditable(false);
        edtConfirmaSenha.setBackground(null);
        edtConfirmaSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtConfirmaSenha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, -1));

        edtSenha.setEditable(false);
        edtSenha.setBackground(null);
        edtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtSenha.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 260, -1));

        edtDataNasc.setBackground(null);
        edtDataNasc.setForeground(new java.awt.Color(0, 0, 0));
        edtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        edtDataNasc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 160, -1));

        chkAtivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chkAtivo.setForeground(new java.awt.Color(0, 0, 0));
        chkAtivo.setText("Ativo");
        jPanel1.add(chkAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        btnAlterarSenha.setBackground(new java.awt.Color(0, 0, 0));
        btnAlterarSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAlterarSenha.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarSenha.setText("Alterar senha");
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        jPanel1.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 140, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        edtNome.setBackground(null);
        edtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
    if (edtSenha.isEditable() == false) {
      edtSenha.setEditable(true);
      edtConfirmaSenha.setEditable(true);
      edtSenha.setBackground(Color.white);
      edtConfirmaSenha.setBackground(Color.white);
      btnAlterarSenha.setText("Cancelar alteração");

      edtSenha.setText("");
      edtConfirmaSenha.setText("");
    } else {
      edtSenha.setEditable(false);
      edtConfirmaSenha.setEditable(false);
      edtSenha.setBackground(Color.gray);
      edtConfirmaSenha.setBackground(Color.gray);
      btnAlterarSenha.setText("Alterar Senha");

      edtSenha.setText("");
      edtConfirmaSenha.setText("");
    }
  }//GEN-LAST:event_btnAlterarSenhaMouseClicked

  private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
    this.dispose();
  }//GEN-LAST:event_btnCancelarMouseClicked

  private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
    if(verificarCampos()){
      gravar();
    }
  }//GEN-LAST:event_btnSalvarMouseClicked

  public boolean verificarCampos() {
    if (edtNome.getText().equals("")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Nome' em branco");
      return false;
    }

    if (!edtNome.getText().matches("^[\\p{L} ]+$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Nome' possui caracteres inválidos");
      return false;
    }

    if (edtEmail.getText().equals("")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Email' em branco");
      return false;
    }
    if (!edtEmail.getText().matches(
            "^[a-z0-9._-]+@[a-z._]+.[a-z._]+$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Email' possui formato inválido");
      return false;
    }

    if (!edtDataNasc.getText().matches(
            "^[0-9]{2}/[0-9]{2}/[0-9]{4}$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Data Nascimento' possui formato inválido."
              + " Ex: 01/01/2010");
      return false;
    }

    if (edtSenha.isEditable()) {
      String senha = new String(edtSenha.getPassword());

      if (senha.length() < 8) {
        JOptionPane.showMessageDialog(null,
                "O campo 'Senha' deve ser maior que 8 caracteres");
        return false;
      }

      if (!senha.equals(new String(edtConfirmaSenha.getPassword()))) {
        JOptionPane.showMessageDialog(null,
                "As senhas não são iguais");
        return false;
      }
    }

    return true;
  }
  
  public void gravar(){
    //cria o objeto usuário
    Usuario usuario = new Usuario();
    
    //preenche os dados do usuário
    usuario.setId_cliente(pkusuario); //pkusuario é o atributo da classe que veio do menu
    usuario.setNome(edtNome.getText());
    usuario.setEmail(edtEmail.getText());

    if (edtSenha.isEditable()) {
      String senha = new String(edtSenha.getPassword());
      String senhaHash = Utils.calcularHash(senha);
      usuario.setSenha(senhaHash);
    }

    Date data = Utils.converterStringToDate(edtDataNasc.getText());
    usuario.setDataNasc(data);

    usuario.setAtivo(chkAtivo.isSelected());
    
    //Passar o objeto usu para o controller
    //enviar para o banco de dados
    UsuarioController controller = new UsuarioController();

    if (controller.alterarUsuario(usuario)) {
      JOptionPane.showMessageDialog(null,
              "Usuário: " + usuario.getNome()
              + " alterado com sucesso!");
      this.dispose();
    } else {
      JOptionPane.showMessageDialog(null,
              "Usuário não será alterado!");
    }
  }
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrAltUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        FrAltUsuario dialog = new FrAltUsuario(new javax.swing.JFrame(), true, 0);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JPasswordField edtConfirmaSenha;
    private javax.swing.JFormattedTextField edtDataNasc;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtNome;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
