/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.RoupaController;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Roupa;

/**
 *
 * @author aluno.saolucas
 */
public class FrAltRoupa extends javax.swing.JDialog {

     private int id_roupa;

    public void setPkRoupa(int id_roupa) {
        this.id_roupa = id_roupa;
    }
    /**
     * Creates new form FrAltRoupa
     */
    public FrAltRoupa(java.awt.Frame parent, boolean modal, int id_roupa) {
        super(parent, modal);
        initComponents();
        setPkRoupa(id_roupa);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        edtPreco = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnAlterarDados = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        edtDescricao = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        edtCor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Alteração de Roupa");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("ID");
        jPanel1.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        edtCodigo.setEditable(false);
        edtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        edtPreco.setEditable(false);
        edtPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtPreco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 380, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setText("Preço");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        btnAlterarDados.setBackground(new java.awt.Color(0, 0, 0));
        btnAlterarDados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAlterarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarDados.setText("Alterar Dados");
        btnAlterarDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarDadosMouseClicked(evt);
            }
        });
        jPanel1.add(btnAlterarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 140, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        edtNome.setEditable(false);
        edtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 140, -1));

        edtDescricao.setEditable(false);
        edtDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 380, -1));

        lblEmail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail1.setText("Descrição");
        jPanel1.add(lblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblNome1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(0, 0, 0));
        lblNome1.setText("Cor");
        jPanel1.add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        edtCor.setEditable(false);
        edtCor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtCor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarDadosMouseClicked
        if (edtNome.isEditable() == false) {
            edtNome.setEditable(true);
            edtPreco.setEditable(true);
            edtCor.setEditable(true);
            edtDescricao.setEditable(true);
            edtNome.setBackground(Color.white);
            edtPreco.setBackground(Color.white);
            edtCor.setBackground(Color.white);
            edtDescricao.setBackground(Color.white);
            btnAlterarDados.setText("Cancelar alteração");

        } else {
            edtNome.setEditable(false);
            edtPreco.setEditable(false);
            edtCor.setEditable(false);
            edtDescricao.setEditable(false);
            edtNome.setBackground(Color.gray);
            edtPreco.setBackground(Color.gray);
            edtCor.setBackground(Color.gray);
            edtDescricao.setBackground(Color.gray);
            btnAlterarDados.setText("Alterar Senha");

        }
    }//GEN-LAST:event_btnAlterarDadosMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if (verificarCampos()) {
            gravar();
            FrAddRoupaTamanho telaAdd = new FrAddRoupaTamanho(null, true);
            telaAdd.setVisible(true);
        }        
    }//GEN-LAST:event_btnSalvarMouseClicked
    
    
    
    
    
    public void gravar() {
        //criar uma instância da classe Usuario 
        //vou preencher os campos
        Roupa rou = new Roupa();
        rou.setNome(edtNome.getText());
        double preco = Double.parseDouble(edtPreco.getText().replace(",", "."));
        rou.setPreco(preco);
        rou.setCor(edtCor.getText());
        rou.setDescricao(edtDescricao.getText());
        rou.setIdRoupa(id_roupa);

        //depois passo o objeto para o controller e ele irá gravar no banco de dados
        RoupaController controller = new RoupaController();
        

        if (controller.alterarRoupa(rou)) {
            JOptionPane.showMessageDialog(null,
                    "Roupa alterada com sucesso");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,
                    "O cadastro não foi gravado");
        }
    }

    public boolean verificarCampos() {
        //Se eu conseguir passar pelas validações retorna true

        //Nome - não pode ter números ou caracteres especiais, apenas letras e espaço
        //Email - ter um formato de email a@a.com
        //Senha - pelo menos 6 dígitos
        //Data - verificar se está no formato de data dd/mm/aaaa
        double preco = Double.parseDouble(edtPreco.getText().replace(",", "."));

        if (!edtNome.getText().matches("^[\\p{L} ]{2,}$")) {//a-
            JOptionPane.showMessageDialog(null,
                    "O campo 'Nome' é inválido. Use apenas letras e espaços.");
            return false;
        }

        if (!edtPreco.getText().matches("^[0-9]{1,3}([.][0-9]{3})*,[0-9]{2}$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Preço' possui formato inválido");
            return false;
        }

        if (!edtCor.getText().matches("^[\\p{L} ]{3,}$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Cor' é inválido. Use apenas letras e espaços.");
            return false;
        }
        if (!edtDescricao.getText().matches("^[\\p{L}\\p{N} ,.\\-]{5,100}$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Descrição' deve ter entre 5 e 100 caracteres válidos.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAltRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAltRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAltRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAltRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAltRoupa dialog = new FrAltRoupa(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarDados;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCor;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
