/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Usuario;
import utils.Utils;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadRoupa extends javax.swing.JDialog {

    /**
     * Creates new form FrCadRoupa
     */
    public FrCadRoupa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtDescricao = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblPreenchimento = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        edtCor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(590, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("R O U P A");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(51, 51, 51));
        lblNome.setText("*Nome");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        edtNome.setBackground(new java.awt.Color(255, 255, 255));
        edtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtNome.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 460, -1));

        edtDescricao.setBackground(new java.awt.Color(255, 255, 255));
        edtDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtDescricao.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 460, -1));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Descrição");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblPreenchimento.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblPreenchimento.setForeground(new java.awt.Color(204, 0, 51));
        lblPreenchimento.setText("*preenchimento obrigatórios");
        jPanel1.add(lblPreenchimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 203, -1));

        btnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 0, 0));
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorderPainted(false);
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 70));

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(51, 51, 51));
        lblCPF.setText("*Preço");
        jPanel1.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        edtPreco.setBackground(new java.awt.Color(255, 255, 255));
        edtPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtPreco.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(edtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 460, -1));

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(51, 51, 51));
        lblTelefone.setText("Cor");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        edtCor.setBackground(new java.awt.Color(255, 255, 255));
        edtCor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edtCor.setForeground(new java.awt.Color(0, 0, 0));
        edtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCorActionPerformed(evt);
            }
        });
        jPanel1.add(edtCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 460, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("CADASTRAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 590, 80));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void edtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCorActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        //verificar os campos se estão preenchidos corretamente
        if(verificarCampos()){
            //Se estiverem corretos vou gravar
            gravar();
        }
        //Senão nada acontece
    }//GEN-LAST:event_btnSalvarMouseClicked
public void gravar(){
    //criar uma instância da classe Usuario 
    //vou preencher os campos
    Usuario usu = new Usuario();
    
    String lSenha = new String(edtSenha.getPassword());
    String lHashSenha = Utils.calcularHash(lSenha); 
    
    //conversão de String para Date
    Date dataNasc = Utils.converterStringToDate(edtDataNasc.getText()); 
    
    usu.setNome(edtNome.getText());
    usu.setCpf(edtCPF.getText());
    usu.setTelefone(edtTelefone.getText());
    usu.setEmail(edtEmail.getText());
    usu.setDataNasc(dataNasc);
    usu.setSenha(lHashSenha); 
    usu.setAtivo(chkAtivo.isSelected());
    //depois passo o objeto para o controller e ele irá gravar no banco de dados
    UsuarioController controller = new UsuarioController();
    
    if(controller.inserirUsuario(usu)){
      JOptionPane.showMessageDialog(null,
              "Usuário gravado com sucesso");
      this.dispose();
    }else{
      JOptionPane.showMessageDialog(null,
              "O cadastro não foi gravado");
    }      
  }
public boolean verificarCampos(){
    //Se eu conseguir passar pelas validações retorna true
    
    //Nome - não pode ter números ou caracteres especiais, apenas letras e espaço
    //Email - ter um formato de email a@a.com
    //Senha - pelo menos 6 dígitos
    //Data - verificar se está no formato de data dd/mm/aaaa
        
    if (!edtNome.getText().matches("^[\\p{L} ]+$")) {//a-
      JOptionPane.showMessageDialog(null,
              "O campo 'Nome' possui formato inválido");
      return false;
    }
    

    if (!edtCPF.getText().matches("^[0-9]{3}\\.([0-9]{3})\\.([0-9]{3})-([0-9]{2})$")) {
    JOptionPane.showMessageDialog(null, 
            "O campo 'CPF' possui formato inválido");
    return false;
}
    
    if (!edtEmail.getText().matches("^[a-z0-9._-]+@[a-z0-9._-]+.[a-z._]+$")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Email' possui formato inválido");
      return false;
    }
    
    
    if(new String(edtSenha.getPassword()).equals("")){
      JOptionPane.showMessageDialog(null, "O campo 'Senha' em branco");
      return false;
    }
    
    String lSenha = new String(edtSenha.getPassword());
    String lConfirmaSenha = new String(edtConfirmaSenha.getPassword());
    
    if(! lSenha.equals(lConfirmaSenha)){
      JOptionPane.showMessageDialog(null, "As senhas não são iguais");
      return false;
    }
    
    if (lSenha.length() < 6) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Senha' deve ter mais de 6 caracteres");
      return false;
    }
    
    if (edtDataNasc.getText().equals("")) {
      JOptionPane.showMessageDialog(null,
              "O campo 'Data de Nascimento' em branco");
      return false;
    }
    
    return true;
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadRoupa dialog = new FrCadRoupa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtCor;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreenchimento;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
