/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.TamanhoController;
import java.net.URL;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Tamanho;
import utils.Utils;

/**
 *
 * @author aluno.saolucas
 */
public class FrCadTamanho extends javax.swing.JDialog {

    /**
     * Creates new form FrCadTamanho
     */
    public FrCadTamanho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        edtSigla = new javax.swing.JTextField();
        lblPreenchimento = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblCPF = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(590, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitulo.setText("T A M A N H O");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(51, 51, 51));
        lblNome.setText("*Sigla");
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        edtSigla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 460, -1));

        lblPreenchimento.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lblPreenchimento.setForeground(new java.awt.Color(204, 0, 51));
        lblPreenchimento.setText("*preenchimento obrigatórios");
        jPanel1.add(lblPreenchimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 203, -1));

        btnVoltar.setBackground(new java.awt.Color(204, 204, 204));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.setBorderPainted(false);
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 70));

        lblCPF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(51, 51, 51));
        lblCPF.setText("Descrição");
        jPanel1.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        edtDescricao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(edtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 460, -1));

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("CADASTRAR");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 590, 80));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        //verificar os campos se estão preenchidos corretamente
        if (verificarCampos()) {
            //Se estiverem corretos vou gravar
            gravar();
        }
        //Senão nada acontece
    }//GEN-LAST:event_btnSalvarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
URL caminhoImagem = getClass().getResource("/images/cadastro.png");

    ImageIcon icon = new ImageIcon(caminhoImagem);

    // Define o ícone da janela
    this.setIconImage(icon.getImage()); 
    }//GEN-LAST:event_formWindowOpened
    public void gravar() {
        Tamanho tam = new Tamanho();

//criar uma instância da classe Usuario 
        //vou preencher os campos
        //conversão de String para Date
        tam.setSigla(edtSigla.getText());
        tam.setDescricao(edtDescricao.getText());

        //depois passo o objeto para o controller e ele irá gravar no banco de dados
        TamanhoController controller = new TamanhoController();

        if (controller.inserirTamanho(tam)) {
            JOptionPane.showMessageDialog(null,
                    "Tamanho gravado com sucesso");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,
                    "O cadastro não foi gravado");
        }
    }

    public boolean verificarCampos() {
        //Se eu conseguir passar pelas validações retorna true

        if (!edtSigla.getText().matches("PP|P|M|G|GG|XG|XXG|XXXG")) {//a-
            JOptionPane.showMessageDialog(null,
                    "O campo 'Sigla' deve conter um tamanho válido (PP, P, M, G, GG, XG, XXG, XXXG).");
            return false;
        }

        if (!edtDescricao.getText().matches("^[\\p{L}\\p{N} ,.\\-]{5,100}$")) {
            JOptionPane.showMessageDialog(null,
                    "O campo 'Descrição' deve conter entre 5 e 100 caracteres válidos.");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCadTamanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCadTamanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCadTamanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCadTamanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrCadTamanho dialog = new FrCadTamanho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtSigla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreenchimento;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
